### PR TITLE
Update UG for Edit Command

### PR DESCRIPTION
**Pull request by sophiien**
Fixed UG for Edit Command based on bug report

### CODE REVIEW

**Review by benmurphyy — CHANGES_REQUESTED** [review]
tag editing needs to be fixed - if every edit of tag removes prv tags and i can only edit 1 tag - then this means i can only ever have 1 tag. standardise tag format with @yokester98 add command, tags cannot have spaces, but can add multiple at one go. I think given this is an inconsistency with the current add command it is considered a functionality bug

**Review by yokester98 — APPROVED** [review]
LGTM

**Review by geraldneo567 — CHANGES_REQUESTED** [review]
Seems to have some minor checkstyle issues causing it to fail the CI

**Comment by sophiien** [comment]
This PR solves the following issues:

-  116, 137, 153, 160: Update UG for edit command
- 120: Fix error message for invalid indexes 
- 122: Throws error message when fields that are not allowed in certain options

**Review by benmurphyy — APPROVED** [review]
LGTM

**Pull request merged**
