### PR TITLE
Add delete command groups

### PR DESCRIPTION
**Pull request by ryanwalterlee**
Format:
(Note: Commands under the sub header Person page can only be used on person page, and likewise for other pages)

On Person Page:

`delete [INDEX]`
* Deletes the person at that index
* The GUI will display the index before the person

`delete [INDEX] p/ e/ t/[TAG] of/`
* p/, e/, t/[TAG], of/ can be entered in any combination, for example, to delete only phone and email, the user can put p/ and e/
* At least 1 of the 4 tags must be entered, otherwise the command above will be executed instead
* Only 0 or 1 of each tag must be provided
* Note that for this command, it actually removes the person object and replaces it with a new one, but the consequences is that it will get removed from its original index and gets added to the bottom of the list

On Module Page:

`delete [INDEX]`
* Deletes the module at that index
* The GUI will display the index before the module

For the following commands, if more than 1 of the following tags are provided, the priority will be in this order. For example, if `prof/1` and `stu/1` is both provided, `delete 1 prof/1` will be prioritised because `prof/` is higher than `stu/` on this list.

`delete [INDEX] prof/[INDEX]`
* Delete professor from module (The original person is not deleted, only removed from the module)
* The first index represents the index for which module to remove a professor from
* The second index (after prof/) represents the index for which professor to remove
* For example, `delete 2 prof/1` would delete the professor at index 1 from the module at index 2

`delete [INDEX] stu/[INDEX]`
* Same as the above command, but index after stu/ represents the student list index to be deleted

`delete [INDEX] g/[GROUPNAME]`
* same as the above command, but group name has to be specified to delete the group with that name

`delete [INDEX] ke/[INDEX]`
* same as the above command, but index after ke/ represents the key event index to be deleted

On Group page:

`delete [INDEX]`
* Deletes the group at that index
* The GUI will display the index before the group

For the following commands, if more than 1 of the following tags are provided, the priority will be in this order. For example, if `mt/1` and `stu/1` is both provided, `delete 1 stu/1` will be prioritised because `stu/` is higher than `mt/` on this list.

`delete [INDEX] stu/[INDEX]`
* Delete student from group
* The first index represents the index for which group to remove the student from
* The second index (after stu/) represents the index for which student to delete
* For example, `delete 2 stu/1` would delete the student at index 1 for the group at index 2

`delete [INDEX] mt/1`
* Delete meeting time from group
* The first index represents the index for which group to remove the meeting time for
* The second index (after mt/) represents the index for which meeting time to delete
* For example, `delete 2 mt/1` would delete the meeting time at index 1 for the group at index 2

On Any Page:

`delete o/module m/[MODULECODE]`
* Deletes the module with the specified `MODULECODE`.
* The module must already exist in the system.
* For example, `delete o/module m/CS2103` removes the module with module code CS2103

`delete o/group m/[MODULECODE] g/[GROUPNAME]`
* Deletes the group specified by `GROUPNAME`, within the module specified by `MODULECODE`.
* Both the module and the subgroup must already exist in the system.
* For example, `delete o/group m/CS2107 g/T04` removes the T04 subgroup from the CS2107 module.

Please let me know if any wrong error messages or bugs, its a big PR but I tried my best with the testing

### CODE REVIEW

**Review by yokester98 — CHANGES_REQUESTED** [review]
Most commands seem to be working nicely done!

Command that isn't working well:
`delete [index] stu/[index]`

When I try to delete a student by index, the wrong index is deleted.

**Comment by ryanwalterlee** [comment]
> Most commands seem to be working nicely done!
> 
> Command that isn't working well: `delete [index] stu/[index]`
> 
> When I try to delete a student by index, the wrong index is deleted.

Ok fixed

**Review by yokester98 — APPROVED** [review]
LGTM! All of the commands work as specified.

Some suggestions you can consider:
Allow user to delete multiple students/meetings at a time.
For example, on the group page, when user wants to delete students from a group.
`delete 1 stu/1 stu/2 stu/3` will delete students in index 1, 2 and 3 from group 1.

Or if a user wants to delete meeting time from a group.
`delete 1 mt/1 mt/2 mt/3` will delete meeting times in index 1, 2 and 3 from group 1.

Finally, if user wants to delete both students and meeting times from a group at the same time
`delete 1 stu/1 mt/1` can delete both student and meeting time from group 1.

**Review by geraldneo567 — APPROVED** [review]
Overall the basic fuctionality is there, deleting seems to work well! Good job!

A few minor things I noticed:

- When on `people` view and I type `delete 1 e/` or `delete 1 p/` to delete phone or email of a person, it seems to switch the order? For example if Ryan and Gerald were at index 1 and 2, after deleting phone number now Gerald and Ryan are at index 1 and 2 ( not sure what would cause this, but not a very serious issue)
- The message for deleting the entire group could maybe specify the module?
image
 Maybe `deleted W16-1 from CS2106` would be helpful, especially if multiple modules have the same groupname in the group list.
- Another thing is that maybe you could make the deleting by group name case-insensitive. For example I tried `delete 1 g/w16-1` on module page but didn't work, needed the case to be the same (can achieve this by converting both user input and group name to lowercase before comparing or using `String::equalsIgnoreCase()` instead of `String::equals()`

Other than that LGTM! The changes I mentioned are relatively minor and do not affect the overall correctness of the command.

**Review by benmurphyy — CHANGES_REQUESTED** [review]
Based on previous reviews - this is almost good to go. Well done! Just apply the patches suggested - especially Gerald's comment regarding the deletion of lowercase.

**Comment by yokester98** [comment]
> Based on previous reviews - this is almost good to go. Well done! Just apply the patches suggested - especially Gerald's comment regarding the deletion of lowercase.

I actually don't think that we should be able to convert the name to uppercase or lowercase in order to delete it. There can be cases where there are two groups such as w16 or W16. It's up to the user when the user creates the group. What do you think? @geraldneo567 @benmurphyy @ryanwalterlee

**Comment by ryanwalterlee** [comment]
> > Based on previous reviews - this is almost good to go. Well done! Just apply the patches suggested - especially Gerald's comment regarding the deletion of lowercase.
> 
> I actually don't think that we should be able to convert the name to uppercase or lowercase in order to delete it. There can be cases where there are two groups such as w16 or W16. It's up to the user when the user creates the group. What do you think? @geraldneo567 @benmurphyy @ryanwalterlee

That is somewhat true, the current checks to allow a group to be added, how does it check if a group of the same name already exists? If it does not check for case then, there could potentially be tp and TP in the same module. And my delete if it equalsIgnoreCase, it will match both of them, and not know which one to delete. We also cannot possibly save group names as lower case as that won't look nice (Imagine your TP transforming to tp).

**Comment by geraldneo567** [comment]
> > Based on previous reviews - this is almost good to go. Well done! Just apply the patches suggested - especially Gerald's comment regarding the deletion of lowercase.
> 
> I actually don't think that we should be able to convert the name to uppercase or lowercase in order to delete it. There can be cases where there are two groups such as w16 or W16. It's up to the user when the user creates the group. What do you think? @geraldneo567 @benmurphyy @ryanwalterlee

Correct me if I'm wrong @yokester98, but i tot the add command currently does not allow duplicate groups to be added?
Meaning if I tried to add w16-1 and W16-1, it will not allow it.

**Comment by ryanwalterlee** [comment]
> * When on `people` view and I type `delete 1 e/` or `delete 1 p/` to delete phone or email of a person, it seems to switch the order? For example if Ryan and Gerald were at index 1 and 2, after deleting phone number now Gerald and Ryan are at index 1 and 2 ( not sure what would cause this, but not a very serious issue)
I wonder if this can be solved in v1.4, because it might not be that easy to maintain. Currently it always adds the edited person to the back of the list

> * The message for deleting the entire group could maybe specify the module?
>   image
>   Maybe `deleted W16-1 from CS2106` would be helpful, especially if multiple modules have the same groupname in the group list.
This is done

**Comment by geraldneo567** [comment]
> > * When on `people` view and I type `delete 1 e/` or `delete 1 p/` to delete phone or email of a person, it seems to switch the order? For example if Ryan and Gerald were at index 1 and 2, after deleting phone number now Gerald and Ryan are at index 1 and 2 ( not sure what would cause this, but not a very serious issue)
> 
> I wonder if this can be solved in v1.4, because it might not be that easy to maintain the index. Currently it always adds the edited person to the back of the list
> 
> > * The message for deleting the entire group could maybe specify the module?
> >   image
> >   Maybe `deleted W16-1 from CS2106` would be helpful, especially if multiple modules have the same groupname in the group list.
> 
> This is done

Nice. regarding the index thing, I dont think it can be fixed in v1.4 cos it kinda changes the behaviour/what is displayed, but imo its not a big issue so should be ok to leave it as is

**Comment by yokester98** [comment]
> > > Based on previous reviews - this is almost good to go. Well done! Just apply the patches suggested - especially Gerald's comment regarding the deletion of lowercase.
> > 
> > 
> > I actually don't think that we should be able to convert the name to uppercase or lowercase in order to delete it. There can be cases where there are two groups such as w16 or W16. It's up to the user when the user creates the group. What do you think? @geraldneo567 @benmurphyy @ryanwalterlee
> 
> Correct me if I'm wrong @yokester98, but i tot the add command currently does not allow duplicate groups to be added? Meaning if I tried to add w16-1 and W16-1 as two different groups to the same module, it will not allow it.

Actually, you're right @geraldneo567 ! When adding groups we do check for duplicate name (case insensitive). @ryanwalterlee Then you would need to add this functionality to delete.

**Comment by ryanwalterlee** [comment]
> Correct me if I'm wrong @yokester98, but i tot the add command currently does not allow duplicate groups to be added? Meaning if I tried to add w16-1 and W16-1 as two different groups to the same module, it will not allow it.

Ok this is done as well, now ignores case

**Pull request merged**
